from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from pyqck.scaffold.names import normalize_package_name


@dataclass(slots=True, frozen=True)
class LibTemplateContext:
    project_name: str
    package_name: str
    profile: str = "lib"
    template: str = "baseline-lib"

    @classmethod
    def from_project_name(cls, project_name: str) -> LibTemplateContext:
        return cls(project_name=project_name, package_name=normalize_package_name(project_name))


def build_lib_template(context: LibTemplateContext) -> dict[Path, str]:
    src_package = Path("src") / context.package_name
    test_module = Path("tests") / f"test_{context.package_name}.py"

    return {
        Path(".gitignore"): _gitignore(),
        Path("README.md"): _readme(context),
        Path("pyproject.toml"): _pyproject(context),
        Path("pyquick.toml"): _pyquick_toml(context),
        src_package / "__init__.py": _package_init(),
        test_module: _test_module(context),
    }


def _gitignore() -> str:
    return """.venv/
__pycache__/
.pytest_cache/
.ruff_cache/
.pyright/
build/
dist/
*.pyc
*.egg-info/
"""


def _readme(context: LibTemplateContext) -> str:
    return f"""# {context.project_name}

Generated by PyQuick using the Python library profile.

## Quickstart

```bash
pyqck install
pyqck test
pyqck check
```

## Project layout

- `src/{context.package_name}/__init__.py`: library package entry
- `tests/test_{context.package_name}.py`: baseline unit test
- `pyquick.toml`: PyQuick command defaults
"""


def _pyproject(context: LibTemplateContext) -> str:
    project_slug = context.project_name.strip().replace(" ", "-").lower()
    return f"""[build-system]
requires = ["hatchling>=1.25.0"]
build-backend = "hatchling.build"

[project]
name = "{project_slug}"
version = "0.1.0"
description = "Python library generated by PyQuick"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.optional-dependencies]
dev = [
  "pyright>=1.1.390",
  "pytest>=8.3.0",
  "ruff>=0.8.0",
]

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-q"
testpaths = ["tests"]

[tool.ruff]
target-version = "py312"
line-length = 100
src = ["src", "tests"]

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP"]

[tool.hatch.build.targets.wheel]
packages = ["src/{context.package_name}"]
"""


def _pyquick_toml(context: LibTemplateContext) -> str:
    return f"""[project]
name = "{context.project_name}"
profile = "{context.profile}"
template = "{context.template}"

[tooling]
packaging = "uv"
linting = "ruff"
testing = "pytest"
typing = "pyright"
running = "uvicorn"

[checks]
pipeline = ["lint", "type", "test"]
stop_on_first_failure = true

[dev]
reload = true
watch = ["src", "tests"]
debounce_ms = 200
checks_mode = "incremental"
fallback_threshold = 8
"""


def _package_init() -> str:
    return """def add(left: int, right: int) -> int:
    return left + right
"""


def _test_module(context: LibTemplateContext) -> str:
    return f"""from {context.package_name} import add


def test_add_returns_sum() -> None:
    assert add(2, 3) == 5
"""
