from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from pyignite.scaffold.names import normalize_package_name


@dataclass(slots=True, frozen=True)
class FastAPITemplateContext:
    project_name: str
    package_name: str
    profile: str = "api"
    template: str = "fastapi"

    @classmethod
    def from_project_name(cls, project_name: str) -> "FastAPITemplateContext":
        return cls(
            project_name=project_name,
            package_name=normalize_package_name(project_name),
        )


def build_fastapi_template(context: FastAPITemplateContext) -> dict[Path, str]:
    package = context.package_name
    src_package = Path("src") / package

    files: dict[Path, str] = {
        Path(".gitignore"): _gitignore(),
        Path("README.md"): _readme(context),
        Path("pyproject.toml"): _pyproject(context),
        Path("pyignite.toml"): _pyignite_toml(context),
        src_package / "__init__.py": _package_init(),
        src_package / "main.py": _main_module(),
        src_package / "api" / "__init__.py": _package_init(),
        src_package / "api" / "router.py": _router_module(),
        Path("tests") / "__init__.py": _package_init(),
    }

    return files


def _gitignore() -> str:
    return """.venv/
__pycache__/
.pytest_cache/
.ruff_cache/
.pyright/
build/
dist/
*.pyc
*.egg-info/
"""


def _readme(context: FastAPITemplateContext) -> str:
    return f"""# {context.project_name}

Generated by PyIgnite using the FastAPI profile (no DB).

## Quickstart

```bash
uv sync
uv run pyignite run
```

## Project layout

- `src/{context.package_name}/main.py`: FastAPI app entrypoint
- `src/{context.package_name}/api/router.py`: API router module
- `pyignite.toml`: PyIgnite command defaults

## Next steps

- Add routes in `src/{context.package_name}/api/router.py`
- Add tests under `tests/`
"""


def _pyproject(context: FastAPITemplateContext) -> str:
    project_slug = context.project_name.strip().replace(" ", "-").lower()
    return f"""[build-system]
requires = ["hatchling>=1.25.0"]
build-backend = "hatchling.build"

[project]
name = "{project_slug}"
version = "0.1.0"
description = "FastAPI service generated by PyIgnite"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "fastapi>=0.115.0",
  "uvicorn>=0.35.0",
]

[project.optional-dependencies]
dev = [
  "httpx>=0.28.0",
  "pyright>=1.1.390",
  "pytest>=8.3.0",
  "ruff>=0.8.0",
]

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-q"
testpaths = ["tests"]

[tool.ruff]
target-version = "py312"
line-length = 100
src = ["src", "tests"]

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP"]

[tool.hatch.build.targets.wheel]
packages = ["src/{context.package_name}"]
"""


def _pyignite_toml(context: FastAPITemplateContext) -> str:
    return f"""[project]
name = "{context.project_name}"
profile = "{context.profile}"
template = "{context.template}"

[tooling]
packaging = "uv"
linting = "ruff"
testing = "pytest"
typing = "pyright"
running = "uvicorn"

[run]
app = "{context.package_name}.main:app"
host = "127.0.0.1"
port = 8000

[checks]
pipeline = ["lint", "type", "test"]
stop_on_first_failure = true
"""


def _package_init() -> str:
    return ""


def _main_module() -> str:
    return """from fastapi import FastAPI

from .api.router import router

app = FastAPI(title="PyIgnite API")
app.include_router(router)
"""


def _router_module() -> str:
    return """from fastapi import APIRouter

router = APIRouter(prefix="/api")


@router.get("/")
def root() -> dict[str, str]:
    return {"status": "ok", "message": "PyIgnite scaffold is running"}
"""
